# coding: utf-8

"""
    Yanport API

    ## À propos Voici quelques ressources qui vous aideront à explorer notre API, si vous avez des problèmes ou des demandes, veuillez contacter le [support](mailto:support@yanport.com). ## REST API Nos services webs utilisent le protocle **HTTPS** sur le port 443, tout accès en HTTP sur le port 80 est bloqué par notre pare-feu. Les échanges de données sont réalisés en **JSON**. ## Authentification Avant de commencer à explorer notre API, vous devez nous [contacter](https://www.yanport.com/contact) afin d'obtenir un [JSON Web Token](https://jwt.io) (**JWT**) qui vous permettra de vous identifier à chaque requêtes. ### JWT (header) La méthode privilégiée pour s'authentifier est de passer à chaque requêtes le token dans le header `Authorization: Bearer {{ JWT }}` en remplaçant `{{ JWT }}` par votre token. ### JWT (query param) Il est aussi possible de passer le token directement en query param de la requête `https://api.yanport.com/?token={{ JWT }}`. (_privilégié le passage par header en production._) ## Pour démarrer Lorsque vous disposez de votre token d'authentification, vous pouvez commencer à explorer notre API grâce au boutton  `Try it out` sur chacun de nos webs services. Mais au préalable, vous devez vous authentifier en cliquant sur le boutton `Authorize `, en remplissant l'input `api_key` avec `Bearer {{ JWT }}`.  **Exemple** `Bearer eyUEkiLCJh...CHCUiBfD63oxoo=` ## Limitation Toutes les requêtes à notre API sont loggées, c'est pourquoi vous devez respecter nos [CGU](https://dev.yanport.com/cgu) afin d'éviter tout usage abusif de notre API. 

    OpenAPI spec version: 1.0
    Contact: dev@yanport.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.biens_api import BiensApi


class TestBiensApi(unittest.TestCase):
    """ BiensApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.biens_api.BiensApi()

    def tearDown(self):
        pass

    def test_properties_count_get(self):
        """
        Test case for properties_count_get

        Nombre de biens
        """
        pass

    def test_properties_count_group_by_group_by_and_sub_group_by_get(self):
        """
        Test case for properties_count_group_by_group_by_and_sub_group_by_get

        Nombre de biens
        """
        pass

    def test_properties_count_group_by_group_by_get(self):
        """
        Test case for properties_count_group_by_group_by_get

        Nombre de biens
        """
        pass

    def test_properties_distribution_get(self):
        """
        Test case for properties_distribution_get

        Disitribution des biens
        """
        pass

    def test_properties_evolution_get(self):
        """
        Test case for properties_evolution_get

        Evolution des biens dans le temps
        """
        pass

    def test_properties_get(self):
        """
        Test case for properties_get

        Rechercher des biens
        """
        pass

    def test_properties_id_get(self):
        """
        Test case for properties_id_get

        Récupérer un bien (ID)
        """
        pass

    def test_properties_ids_get(self):
        """
        Test case for properties_ids_get

        Récupérer des biens (ID)
        """
        pass

    def test_properties_percentiles_get(self):
        """
        Test case for properties_percentiles_get

        Indicateurs de références
        """
        pass

    def test_properties_percentiles_group_by_group_by_get(self):
        """
        Test case for properties_percentiles_group_by_group_by_get

        Indicateurs de réferences
        """
        pass

    def test_properties_stats_get(self):
        """
        Test case for properties_stats_get

        Statistiques sur les biens
        """
        pass

    def test_properties_stats_group_by_group_by_and_sub_group_by_get(self):
        """
        Test case for properties_stats_group_by_group_by_and_sub_group_by_get

        Statistiques sur les biens
        """
        pass

    def test_properties_stats_group_by_group_by_get(self):
        """
        Test case for properties_stats_group_by_group_by_get

        Statistiques sur les biens
        """
        pass

    def test_properties_stock_evolution_get(self):
        """
        Test case for properties_stock_evolution_get

        L'évolution du stock de biens
        """
        pass


if __name__ == '__main__':
    unittest.main()
